export type Settings = {
  DATA_VARIANT_NAMES: boolean;
  DATA_EMPTY_VARIANTS: boolean;
  DATA_INVALID_VARIANT: boolean;
  DATA_INVALID_COMBINATIONS: boolean;
  DATA_LAYOUT: 'LAYOUT' | 'PARENT_CHILDREN' | 'BOTH';
  DATA_STYLES_VARIABLE_FORMAT: 'NAME_WITH_COLLECTION' | 'NAME' | 'OBJECT';
  DETAILS: 'FULL' | 'LAYERED';
  OUTPUT: boolean;
  OUTPUT_REPLACE: boolean;
  OUTPUT_DATA: boolean;
  OUTPUT_STYLING: boolean;
  OUTPUT_ANATOMY: boolean;
  OUTPUT_LAYOUT: boolean;
  OUTPUT_PROPS: boolean;
  OUTPUT_MODES: boolean;
  ANATOMY_CONTENT: 'CANVAS' | 'DEV_MODE';
  ANATOMY_EXPOSE_BOOLEAN_PROP_LAYERS: boolean;
  FORMAT_OUTPUT: 'YAML' | 'JSON';
  FORMAT_KEYS: 'SAFE' | 'CAMEL' | 'SNAKE' | 'KEBAB' | 'PASCAL' | 'TRAIN';
  FORMAT_COLOR: 'HEX' | 'HSLA';
  FORMAT_CUSTOM_COLORS: boolean;
  FORMAT_CUSTOM_SPACING: boolean;
  FORMAT_CUSTOM_TEXT_STYLES: boolean;
  SIMPLIFY_STYLES?: boolean;
  SIMPLIFY_VARIABLES?: boolean;
  SUBCOMPONENTS: boolean;
  SUBCOMPONENT_NAME_PATTERN: string;
  VARIANT_DEPTH: 1 | 2 | 3 | 9999;
};

export const DEFAULT_SETTINGS: Settings = {
  DATA_VARIANT_NAMES: true,
  DATA_EMPTY_VARIANTS: false,
  DATA_INVALID_VARIANT: false,
  DATA_INVALID_COMBINATIONS: true,
  DATA_LAYOUT: 'LAYOUT',
  DATA_STYLES_VARIABLE_FORMAT: 'NAME',
  DETAILS: 'LAYERED',
  OUTPUT: true,
  OUTPUT_REPLACE: false,
  OUTPUT_DATA: true,
  OUTPUT_STYLING: true,
  OUTPUT_ANATOMY: true,
  OUTPUT_LAYOUT: true,
  OUTPUT_PROPS: true,
  OUTPUT_MODES: false,
  ANATOMY_CONTENT: 'CANVAS',
  ANATOMY_EXPOSE_BOOLEAN_PROP_LAYERS: false,
  FORMAT_OUTPUT: 'JSON',
  FORMAT_KEYS: 'SAFE',
  FORMAT_COLOR: 'HEX',
  FORMAT_CUSTOM_COLORS: false,
  FORMAT_CUSTOM_SPACING: false,
  FORMAT_CUSTOM_TEXT_STYLES: false,
  SUBCOMPONENTS: false,
  SUBCOMPONENT_NAME_PATTERN: '{C} / _ / {S}',
  VARIANT_DEPTH: 9999,
};
